### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by danillotparreira** [danillotparreira/gerenciador#10]
# Usuário

- [ ]  Castrastro usuario
- [ ]  Login Usuario
- [ ]  Controle permissão
- [ ]  Permissão por Usuário ou Grupo.
- [ ]  Recuperação Senha
- [ ]  Envio Email
- [ ]  Cadastro Pessoa
- [ ] Cadastro Pessoa Física
- [ ] Cadastro Pessoa Jurídica
- [ ] Funcionario
- [ ] Fornecedor
- [ ] Cliente

# Produtos
